# Generated by Django 4.2.16 on 2024-09-10 08:48

import apps.courses.validations
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('code', models.CharField(max_length=6, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('academic_units', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)])),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('level', models.CharField(blank=True, max_length=2, null=True)),
                ('program_code', models.CharField(blank=True, max_length=3, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('prerequisite', models.CharField(blank=True, max_length=300, null=True)),
                ('mutually_exclusive', models.CharField(blank=True, max_length=300, null=True)),
                ('not_available', models.CharField(blank=True, max_length=300, null=True)),
                ('not_available_all', models.CharField(blank=True, max_length=300, null=True)),
                ('offered_as_ue', models.BooleanField(default=True)),
                ('offered_as_bde', models.BooleanField(default=True)),
                ('grade_type', models.CharField(blank=True, max_length=300, null=True)),
                ('not_offered_as_core_to', models.CharField(blank=True, max_length=300, null=True)),
                ('not_offered_as_pe_to', models.CharField(blank=True, max_length=300, null=True)),
                ('not_offered_as_bde_ue_to', models.CharField(blank=True, max_length=300, null=True)),
                ('department_maintaining', models.CharField(blank=True, max_length=50, null=True)),
                ('program_list', models.CharField(blank=True, max_length=1000, null=True)),
                ('exam_schedule', models.CharField(blank=True, max_length=53, validators=[apps.courses.validations.validate_exam_schedule])),
                ('common_schedule', models.CharField(max_length=192, validators=[apps.courses.validations.validate_weekly_schedule])),
                ('common_information', models.TextField(blank=True, null=True, validators=[apps.courses.validations.validate_information])),
            ],
            options={
                'verbose_name_plural': 'Courses',
            },
        ),
        migrations.CreateModel(
            name='CourseIndex',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.CharField(max_length=5, unique=True, validators=[django.core.validators.RegexValidator(code='invalid_format', message='The value must be 5 numeric digits.', regex='^\\d{5}$')])),
                ('information', models.TextField(validators=[apps.courses.validations.validate_information])),
                ('schedule', models.CharField(max_length=192, validators=[apps.courses.validations.validate_weekly_schedule])),
                ('filtered_information', models.TextField(blank=True, null=True, validators=[apps.courses.validations.validate_information])),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='indexes', to='courses.course')),
            ],
            options={
                'verbose_name_plural': 'Course Indexes',
            },
        ),
    ]
