# Generated by Django 4.2.16 on 2024-09-10 11:41

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseProgram',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300, unique=True)),
                ('value', models.CharField(max_length=300, unique=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('year', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('courses', models.ManyToManyField(related_name='programs', to='courses.course')),
            ],
            options={
                'verbose_name_plural': 'Course Programs',
            },
        ),
    ]
