# Generated by Django 4.2.16 on 2024-09-11 02:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_courseprefix'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='program_code',
        ),
        migrations.AddField(
            model_name='course',
            name='prefix',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='courses.courseprefix'),
        ),
    ]
