# Generated by Django 5.1.1 on 2024-10-03 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_remove_course_program_code_course_prefix'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='mutually_exclusive',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='not_available',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='not_available_all',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='not_offered_as_bde_ue_to',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='not_offered_as_core_to',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='not_offered_as_pe_to',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='prerequisite',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
