# Generated by Django 5.1.1 on 2024-12-09 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_rename_course_courseindex_course_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='mutually_exclusive',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='not_available',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='not_available_all',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='not_offered_as_bde_ue_to',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='not_offered_as_core_to',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='not_offered_as_pe_to',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='prerequisite',
            field=models.TextField(blank=True, null=True),
        ),
    ]
