# Generated by Django 5.1.1 on 2024-12-12 14:36

import apps.courses.validations
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0008_courseschedule_common_schedule_for_course'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='common_schedule',
            field=models.CharField(max_length=192, null=True, validators=[apps.courses.validations.validate_weekly_schedule]),
        ),
    ]
