# Generated by Django 5.1.1 on 2024-12-12 14:38

import apps.courses.validations
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0009_alter_course_common_schedule'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='common_schedule',
            field=models.CharField(blank=True, max_length=192, null=True, validators=[apps.courses.validations.validate_weekly_schedule]),
        ),
    ]
