# Generated by Django 5.1.1 on 2024-12-12 15:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0010_alter_course_common_schedule'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courseschedule',
            name='index',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='courses.courseindex'),
        ),
    ]
