# Generated by Django 5.1.1 on 2024-12-21 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0011_alter_courseschedule_index'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='prefix',
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
    ]
