# Generated by Django 5.1.1 on 2024-12-26 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0013_courseprerequisite_prerequisitegraph'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='prerequisites_tree',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
