# Generated by Django 5.1.1 on 2025-01-18 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0014_course_prerequisites_tree'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='scraped_for',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
