# Generated by Django 4.2.16 on 2024-09-12 07:26

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FeedbackForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact', models.CharField(blank=True, max_length=100)),
                ('type', models.CharField(choices=[('Bug Report', 'Bug Report'), ('Feature Request', 'Feature Request'), ('Improvement Suggestion', 'Improvement Suggestion'), ('Request Assistance', 'Request Assistance'), ('Others', 'Others')], max_length=30)),
                ('title', models.CharField(max_length=100)),
                ('details', models.TextField()),
                ('creation_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('acknowledged', models.BooleanField(default=False)),
                ('resolved', models.BooleanField(default=False)),
                ('internal_notes', models.TextField(blank=True)),
                ('response', models.TextField(blank=True)),
            ],
        ),
    ]
